apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: influxdb
    fsType: ext4
